### ISSUE TITLE
获取书籍详情/v1/book/detail/{isbn}结果为空

### ISSUE THREAD

**Issue by zyitst** [Away0x/7yue_api_server#3]
请问是数据库中没有写入数据吗？

**Comment by Away0x** [comment]
> 请问是数据库中没有写入数据吗？

这个接口是去调用豆瓣 api 的，https://api.douban.com/v2/book/isbn/xxx 现在好像这个 api 有变动了吧

**Comment by Away0x** [comment]
> 请问是数据库中没有写入数据吗？

改了下 api 地址，现在好了

**Comment by zyitst** [comment]
> > 请问是数据库中没有写入数据吗？
> 
> 改了下 api 地址，现在好了

谢谢~
