### ISSUE TITLE
书籍详情接口无法使用

### ISSUE THREAD

**Issue by alexkie007** [Away0x/7yue_api_server#4]
大佬 获取书籍详情 API无法使用了 好像是鱼书的api发生了变更 可以告知一下 鱼书最新api的使用方式么

**Comment by Away0x** [comment]
不好意思，我也不太清楚，你可以去抓包看一下哈

**Comment by alexkie007** [comment]
搜了一下  域名好像变成了 http://t.talelin.com/ 大佬有空修改一下你已经部署好的服务么

**Comment by Away0x** [comment]
> 搜了一下 域名好像变成了 http://t.talelin.com/ 大佬有空修改一下你已经部署好的服务么

改好了

**Comment by alexkie007** [comment]
多谢
