### ISSUE TITLE
windows下怎么运行项目

### ISSUE THREAD

**Issue by fanaishiren** [Away0x/7yue_api_server#5]
不太懂这个项目,想在本地跑起来试试,请问怎么跑起来?只需要看到接口列表和数据就行  么么哒

**Comment by Away0x** [comment]
> 不太懂这个项目,想在本地跑起来试试,请问怎么跑起来?只需要看到接口列表和数据就行 么么哒

你好，项目运行需要 go 语言环境的，可以参照项目 README.md 里面的步骤 (dev/pro) 开发模式或者生产环境部署模式运行
